baseURL: "https://thubZai.github.io/" 
title: Yash Thube 
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: papers/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Resume
          url: cv_rosa2.pdf
          weight: 3 
        # - name: Photography
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "Machine Learning Research & Engineering"
    author: Yash Thube
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yash Thube
          subtitle: "I care about making machines intuitively understand space, time & physics through world models"
          imageUrl: "IMG_2987.jpeg"
          imageWidth: 160
          imageHeight: 190
          imageTitle: Yash
          buttons:
            - name: Publications
              url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
           # - name: Newsletter
           #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            - name: Talks
              url: talks/
            - name: Resume
              url: cv_rosa2.pdf
            #- name: Archive
            #  url: archive/
    socialIcons:
        # - name: CV
        #   url: cv_rosa.pdf
        - name: Email
          url: mailto:thubeyash09@gmail.com
        - name: GitHub
          url: https://github.com/thubZ09
        - name: LinkedIn
          url: https://www.linkedin.com/in/thube09/
        - name: CV
          url: 
      

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Thube"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
