baseURL: "https://thubZai.github.io/" 
title: Yash Thube 
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: papers/
          weight: 1
        - name: Research
          url: research/
          weight: 2
        - name: Brain Dump
          url: https://www.notion.so/Welcome-to-my-secondary-brain-c7dc4ccf8be54449b9b248ec9378c219
          weight: 3
        #- name: Random Musings
        #  url: musings
        #  weight: 3 
        # - name: Photography
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "Machine Learning Research & Engineering"
    author: Yash Thube
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yash Thube
          subtitle: "I care about making machines intuitively understand space, time & physics through world models. Moving beyond next-token prediction, mental simulation engines that learn from mistakes, plan with imagination, and adapt to our physical world.<br><br>Works shaping my thinking: [LeCun's JEPA/V-JEPA](https://arxiv.org/abs/2301.08243), [NVIDIA Cosmos](https://www.nvidia.com/en-in/ai/cosmos/), Sakana AI's work in open-endedness, DeepMind's [Dreamer series](https://danijar.com/) & [Genie](https://deepmind.google/blog/genie-3-a-new-frontier-for-world-models/), World Labs, Physical Intelligence (Ï€), and Genesis.<br>Currently exploring how latent dynamics can improve VLMs/VLAMs spatial, casual understanding and predictive planning. Always open to collaborations!"
          imageUrl: "IMG_2987.jpeg"
          imageWidth: 170
          imageHeight: 205
          imageTitle: Yash
          buttons:
            - name: Projects
              url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
           # - name: Newsletter
           #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            - name: Brain Dump
              url: https://www.notion.so/Welcome-to-my-secondary-brain-c7dc4ccf8be54449b9b248ec9378c219
            #- name: Resume
            #  url: cv_rosa2.pdf
            #- name: Archive
            #  url: archive/
    socialIcons:
        # - name: CV
        #   url: cv_rosa.pdf
        - name: Email
          url: mailto:thubeyash09@gmail.com
        - name: GitHub
          url: https://github.com/thubZ09
        - name: LinkedIn
          url: https://www.linkedin.com/in/thube09/
        - name: CV
          url: CV_yt.pdf
      

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yash Thube"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
